version: "3"

services:
  # Database
  db:
    platform: linux/x86_64
    container_name: todo-mysqldb
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - "./schema:/docker-entrypoint-initdb.d"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tododb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - todo-network

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - todo-network

  todoapi:
    container_name: todo-api
    build: 
      context: ./api
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      - todo-network

networks:
  todo-network:

volumes:
  db_data: